version: "3.9"

services:
  caddy:
    container_name: caddy
    image: caddy:2.7-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 5173:5173
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 3000:3000
    environment:
      PORT: ${SERVER_PORT}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
